name: retrieve-vault
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'terraform/**'
      - '*.md'
jobs:
  get-secret:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    name: Retrieve Vault Secret
    steps:
      - name: Get JWT
        id: auth-token
        run: |
            export TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
            echo $TOKEN | jq .value | base64
      - name: Retrieve Vault Secret
        id: retrieve-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ vars.VAULT_ADDR }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          path: jwt-github
          role: "gha-workflow"
          method: jwt
          exportToken: true
          secrets: |
              prod/kv/data/foo bar | SECRET_BAR ;
      - name: verify secret was retrieved
        run: |
          echo $SECRET_BAR | base64
#      - name: Revoke Vault Token
#        if: always()
#        run: |
#          curl -X POST -sv --fail-with-body \
#            -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
#            ${{ vars.VAULT_ADDR }}/v1/auth/token/revoke-self
  get-additional-secret:
    environment: "foo"
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    name: Retrieve Vault Secret ELECTRIC BOOGALOO
    steps:
      - name: Get JWT
        id: auth-token
        run: |
            export TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
            echo $TOKEN | jq .value | base64
      - name: Retrieve Vault Secret
        id: retrieve-secrets-additional
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ vars.VAULT_ADDR }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          path: jwt-github
          role: "gha-workflow"
          method: jwt
          exportToken: true
          secrets: |
              prod/kv/data/norf qux | SECRET_BAR ;
      - name: verify secret was retrieved
        run: |
          echo $SECRET_BAR | base64
      - name: Revoke Vault Token
        if: always()
        run: |
          curl -X POST -sv --fail-with-body \
            -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
            ${{ vars.VAULT_ADDR }}/v1/auth/token/revoke-self
