name: retrieve-vault
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - '*.md'
jobs:
  get-secret:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    name: Run Step 1
    steps:
      - name: Retrieve Vault Secret
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ vars.VAULT_ADDR }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          path: jwt-github
          role: gha-workflow
          method: jwt
          secrets: |
              prod/kv/data/foo bar | SECRET_BAR ;
      - name: Revoke Vault Token
        if: always()
        run: |
          curl -X POST -sv --fail-with-body \
            -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
            ${{ vars.VAULT_ADDR }}/v1/auth/token/revoke-self
      - name: verify secret was retrieved
        run: |
          echo $SECRET_BAR | base64
